import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayout from "@/component/layouts/MainLayout";
import StoreProvider from "./StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mr-Electronic",
  description: "Generated by Mr-Electronic",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
 
return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased {font-geist-mono} bg-black/[0.96] antialiased `}
      >
        <MainLayout>
        {/* {children} */}
        <StoreProvider>{children}</StoreProvider>
        </MainLayout>
      </body>
    </html>
  );
}